version: '2'
services:
    elasticsearch:
      image: elasticsearch:5
      command: elasticsearch
      environment:
        # This helps ES out with memory usage
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - LOGSPOUT=ignore
      volumes:
        # Persist elasticsearch data to a volume
        - elasticsearch:/usr/share/elasticsearch/data
        # Extra ES configuration options
        - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "9200:9200"
        - "9300:9300"

    logstash_indexing:
      image: logstash:5
      command: logstash -w 4 -f /etc/logstash/conf.d/logstash.conf
      environment:
        # This helps Logstash out if it gets too busy
        - LS_HEAP_SIZE=2048m
        - LOGSPOUT=ignore

      volumes:
        # volume mount the logstash config
        - ./logstash_indexing/logstash.conf:/etc/logstash/conf.d/logstash.conf
        - ./logstash_indexing/logstash-forwarder.key:/etc/logstash/logstash-forwarder.key
        - ./logstash_indexing/logstash-forwarder.crt:/etc/logstash/logstash-forwarder.crt
        - /etc/localtime:/etc/localtime:ro
      ports:
        #- "12201:12201/udp"
        - "5000:5000"
        - "5001:5001"
        - "5002:5002/udp"
      links:
        - elasticsearch

    kibana:
      image: kibana:5
      environment:
        # Point Kibana to the elasticsearch container
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - LOGSPOUT=ignore
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      volumes:
        - /etc/localtime:/etc/localtime:ro

    kopf:
      image: lmenezes/elasticsearch-kopf:latest
      ports:
        - "8080:80"
      environment:
        KOPF_ES_SERVERS: "elasticsearch:9200"
        KOPF_SERVER_NAME: "kopf"
        LOGSPOUT: ignore

      volumes:
        - /etc/localtime:/etc/localtime:ro
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

    msgqueue:
      image: rabbitmq:3-management
      hostname: msgqueue
      #environment:
         #- RABBITMQ_ERLANG_COOKIE="secret"
         #- RABBITMQ_DEFAULT_USER="user"
         #- RABBITMQ_DEFAULT_PASS="password"
         #- RABBITMQ_HIPE_COMPILE="1"

      volumes:
         - "msgqueue:/var/lib/rabbitmq"
         #- "./msgqueue/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"

      ports:
         - 8090:15672

    logstash_shipping:
      image: logstash:5
      command: logstash -w 4 -f /etc/logstash/conf.d/logstash.conf
      environment:
        # This helps Logstash out if it gets too busy
        - LS_HEAP_SIZE=2048m
        - LOGSPOUT=ignore

      volumes:
        # volume mount the logstash config
        - ./logstash_shipping/logstash.conf:/etc/logstash/conf.d/logstash.conf
        #- ./logstash_shipping/logstash-forwarder.key:/etc/logstash/logstash-forwarder.key
        #- ./logstash_shipping/logstash-forwarder.crt:/etc/logstash/logstash-forwarder.crt
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "12201:12201/udp"
        - "6000:6000"
        - "6001:6001"
        - "6002:6002/udp"
        - "9000:9000"
      links:
        - elasticsearch
        - msgqueue

      depends_on:
        - msgqueue
        - elasticsearch

    logspout:
      build: ./logspout
      ports:
         - "8000:80"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /etc/localtime:/etc/localtime:ro
      command: /bin/dockerize -timeout 200s -wait tcp://logstash_shipping:6000 /bin/logspout
      environment:
         - ROUTE_URIS=tcp://logstash_shipping:6000
         - LOGSPOUT=ignore

      links:
         - logstash_shipping

      depends_on:
         - logstash_shipping

    cadvisor:
      image: google/cadvisor-canary
      hostname: cadvisor
      privileged: true
      ports:
        - "81:8080"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker/:/var/lib/docker:ro"
      
    nginx:
      image: nginx:latest
      ports:
         - "80:80"
      depends_on:
         - logspout
      environment:
         - NGINX_PORT=80
      volumes:
         - /etc/localtime:/etc/localtime:ro

      depends_on:
         - logstash_shipping

#      logging:
#        driver: syslog
#        options:
#          syslog-address: "tcp://logstash:5001"

#    mysql:
#      image: mysql
#      environment:
#        MYSQL_ROOT_PASSWORD: "password"
#      volumes:
#        - mysqldata:/var/lib/mysql
#        - mysqllog:/var/log/mysql/mysql
#        - /etc/localtime:/etc/localtime:ro
#
#      depends_on:
#        - logspout
#
#    wordpress:
#      image: wordpress
#      links:
#         - mysql:mysql
#      depends_on:
#         - mysql
#      ports:
#         - "8011:80"
#      volumes:
#         - wordpressdata:/var/www
#         - wordpresslog:/var/log
#      environment:
#         WORDPRESS_DB_PASSWORD: "password"
#
#    mysql_log:
#       image: debian
#       command: tail -F /mnt/mysql/error.log
#       volumes:
#         - mysqllog:/mnt
#       links:
#         - mysql
#       depends_on:
#         - mysql

#    load_test:
#       image: russmckendrick/ab
#       links:
#          - wordpress:wordpress
#       depends_on:
#          - wordpress
#       command: ab -k -n 10000 -c 5 http://wordpress:80/test

volumes:
  elasticsearch:
  mysqldata:
  mysqllog:
  wordpressdata:
  wordpresslog:
  msgqueue:

